# .prettierrc.yml
# see: https://prettier.io/docs/en/options.html
printWidth: 120
semi: true
singleQuote: true
trailingComma: all
jsxBracketSameLine: false
jsxSingleQuote: false
arrowParens: avoid
bracketSpacing: false
endOfLine: auto
proseWrap: preserve
requirePragma: false
tabWidth: 2
useTabs: false
parser: typescript # babel-ts
quoteProps: as-needed
plugins: ["prettier-plugin-svelte"]
overrides:
  - files: "*.json"
    options:
      printWidth: 200
  - files: "*.svelte"
    options:
      parser: "svelte"
